@startuml DCU_PlataformaWebAltoNivel
left to right direction

skinparam dpi 150
skinparam usecasePadding 25
skinparam actorPadding 80
skinparam packagePadding 50
skinparam wrapWidth 200

skinparam nodesep 20
skinparam ranksep 100

actor Alumno
actor Docente
actor Administrador
actor "Google OAuth 2.0" as GoogleOAuth2

package "Plataforma Gamificada Algoritmia (PGA)"{
    package "Plataforma web"{
        usecase "Gestión de usuarios" as GestionUsuarios
        usecase "Gestión de instituciones" as GestionInstituciones
        usecase "Gestión de cursos" as GestionCursos
        usecase "Seguimiento académico" as SeguimientoAcademico
        usecase "Gestión de auditoría" as GestionAuditoria
    }

    Alumno --> GestionUsuarios
    Alumno --> GestionCursos
    Alumno --> SeguimientoAcademico
    
    Administrador -up-> GestionUsuarios
    Administrador -up-> GestionInstituciones
    Administrador -up-> GestionCursos
    Administrador -up-> GestionAuditoria

    Docente --> GestionUsuarios
    Docente --> GestionCursos
    Docente --> SeguimientoAcademico

    GoogleOAuth2 -up-> GestionUsuarios
}

@enduml