@startuml Videojuego_CU
left to right direction

skinparam usecasePadding 15
skinparam actorPadding 15
skinparam wrapWidth 200

actor Alumno

package "Videojuego" {
  usecase "UC-40 Iniciar sesión en el videojuego" as UC40
  usecase "UC-41 Resolver misión" as UC41
  usecase "UC-42 Seleccionar misión" as UC42
  usecase "UC-43 Diseñar solución con lenguaje gamificado" as UC43
  usecase "UC-44 Agregar acción" as UC44
  usecase "UC-45 Declarar variable" as UC45
  usecase "UC-46 Asignar valor a variable" as UC46
  usecase "UC-47 Agregar estructura condicional" as UC47
  usecase "UC-48 Agregar estructura repetitiva" as UC48
  usecase "UC-49 Agregar procedimiento" as UC49
  usecase "UC-50 Consultar manual del héroe" as UC50
  usecase "UC-51 Ejecutar misión" as UC51
  usecase "UC-52 Evaluar misión" as UC52
  usecase "UC-53 Generar feedback" as UC53
  usecase "UC-54 Aceptar feedback" as UC54
  usecase "UC-55 Ver progreso en el juego" as UC55
  usecase "UC-56 Consultar inventario" as UC56

  Alumno --> UC40
  Alumno --> UC41
  Alumno --> UC55
  Alumno --> UC56

  UC41 --> UC42 : <<include>>
  UC41 --> UC43 : <<include>>
  UC41 --> UC51 : <<include>>
  UC41 --> UC52 : <<include>>
  UC41 --> UC53 : <<include>>

  UC43 --> UC44 : <<include>>
  UC43 --> UC45 : <<extend>>
  UC43 --> UC46 : <<extend>>
  UC43 --> UC47 : <<extend>>
  UC43 --> UC48 : <<extend>>
  UC43 --> UC49 : <<extend>>
  UC43 --> UC50 : <<extend>>

  UC53 --> UC54 : <<extend>>
}

@enduml
