@startuml DCU_Expandido
left to right direction

skinparam dpi 150
skinparam usecasePadding 25
skinparam actorPadding 100
skinparam packagePadding 20
skinparam wrapWidth 200

skinparam nodesep 30
skinparam ranksep 300

skinparam ArrowThickness 0.5
skinparam ArrowColor Black


actor Administrador
actor Docente
actor Alumno
actor "Google OAuth 2.0" as GoogleOAuth2
actor Videojuego

package "Plataforma Web - PGA"{
  'Subsistemas'
  package "Gestión de usuarios" {
    usecase "UC-01 Alta usuario" as UC01
    usecase "UC-02 Modificar usuario" as UC02
    usecase "UC-03 Buscar usuario" as UC03
    usecase "UC-04 Baja usuario" as UC04

    'Relaciones'
    Administrador --> UC01
    Administrador --> UC02
    Alumno --> UC02
    Docente --> UC02
    UC02 ..> UC03 : <<include>>
    Administrador --> UC04
    UC04 ..> UC03 : <<include>>
  }

  package "Gestión de institución y cursos" {
    usecase "UC-05 Alta institución" as UC05
    usecase "UC-06 Modificar institución" as UC06
    usecase "UC-07 Alta curso" as UC07
    usecase "Modalidad presencial" as UC07A
    usecase "Modalidad virtual" as UC07B
    usecase "Modalidad mixta" as UC07C
    usecase "UC-08 Modificar curso" as UC08
    usecase "UC-09 Buscar curso" as UC09
    usecase "UC-10 Baja curso" as UC10
    usecase "UC-11 Unirse a un curso" as UC11
    usecase "UC-12 Habilitar siguiente capítulo" as UC12
    usecase "UC-13 Finalizar curso" as UC13

    'Relaciones'
    'AM Institución
    Administrador --> UC05
    Administrador --> UC06
    'ABM Cursos
    Administrador --> UC07
    UC07 <.. UC07A : <<extend>>
    UC07 <.. UC07B : <<extend>>
    UC07 <.. UC07C : <<extend>>
    Administrador --> UC08
    Docente --> UC08
    Administrador --> UC10
    UC08 ..> UC09 : <<include>>
    UC10 ..> UC09 : <<include>>
    'Unirse a curso
    Alumno --> UC11
    'Habilitar capítulo
    Docente --> UC12
    Docente --> UC13
    UC13 ..> UC09 : <<include>>
  }

  package "Progreso y estadísticas" {
    usecase "UC-14 Consultar progreso de alumnos" as UC14
    usecase "Progreso total" as UC14A
    usecase "Progreso en capítulo" as UC14B
    usecase "UC-15 Generar reporte de progreso" as UC15
    usecase "UC-16 Consultar dificultades de alumnos" as UC16
    usecase "UC-17 Sincronizar progreso de alumno" as UC17
    usecase "UC-18 Actualizar dificultades de alumno" as UC18
    usecase "UC-19 Consultar mi progreso" as UC19
    usecase "UC-20 Consultar mis dificultades" as UC20

    'Relaciones'
    Docente --> UC14
    UC14 <.. UC14A : <<extend>>
    UC14 <.. UC14B : <<extend>>
    Docente --> UC15
    Docente --> UC16
    Videojuego --> UC17
    Videojuego --> UC18
    Alumno --> UC19
    Alumno --> UC20
  }

  package "Gestión de sesiones de refuerzo" {
    usecase "UC-25 Crear sesión de refuerzo" as UC25
    usecase "UC-26 Modificar sesión de refuerzo" as UC26
    usecase "UC-27 Buscar sesión de refuerzo" as UC27
    usecase "UC-28 Cancelar sesión de refuerzo" as UC28
    usecase "UC-29 Indicar asistencia a sesión" as UC29

    'Relaciones'
    Docente --> UC25
    Docente --> UC26
    Docente --> UC28
    UC26 ..> UC27 : <<include>>
    UC28 ..> UC27 : <<include>>
    Docente --> UC29
    Alumno --> UC29
    UC29 ..> UC27 : <<include>>
  }

  package "Auditoría" {
    usecase "UC-30 Consultar registros de auditoría" as UC30
    usecase "Exportar registros de auditoría" as UC30A

    'Relaciones'
    Administrador --> UC30
    UC30 <.. UC30A : <<extend>>
  }

  package "Seguridad y autenticación" {
    usecase "UC-31 Iniciar sesión" as UC31
    usecase "Iniciar sesión normal" as UC31A
    usecase "Iniciar sesión con Google" as UC31B
    usecase "UC-32 Registrarse" as UC32
    usecase "Registro normal" as UC32A
    usecase "Registro con Google" as UC32B
    usecase "UC-33 Cerrar sesión" as UC33

    'Relaciones'
    Administrador --> UC31
    Administrador --> UC33
    Docente --> UC31
    Docente --> UC33
    Alumno --> UC31
    Alumno --> UC32
    Alumno --> UC33
    UC31 <.. UC31A : <<extend>>
    UC31 <.. UC31B : <<extend>>
    UC32 <.. UC32A : <<extend>>
    UC32 <.. UC32B : <<extend>>
    GoogleOAuth2 -up-> UC31B
    GoogleOAuth2 -up-> UC32B
  }

}
@enduml