@startuml DCU_Expandido
left to right direction

skinparam dpi 150
skinparam usecasePadding 25
skinparam actorPadding 100
skinparam packagePadding 20
skinparam wrapWidth 200

skinparam nodesep 30
skinparam ranksep 300

skinparam ArrowThickness 0.5
skinparam ArrowColor Black


actor Administrador
actor Docente
actor Alumno
actor "Google OAuth 2.0" as GoogleOAuth2
actor Videojuego

package "Plataforma Web - PGA"{
  'Subsistemas'
  package "Gestión de usuarios" {
    usecase "UC-01 Alta usuario" as UC01
    usecase "UC-02 Modificar usuario" as UC02
    usecase "UC-03 Buscar usuario" as UC03
    usecase "UC-04 Baja usuario" as UC04
    usecase "UC-05 Modificar datos personales" as UC05

    'Relaciones'
    Administrador --> UC01
    Administrador --> UC02
    UC02 ..> UC03 : <<include>>
    Administrador --> UC04
    UC04 ..> UC03 : <<include>>
    Alumno --> UC05
    Docente --> UC05
  }

  package "Gestión de institución y cursos" {
    usecase "UC-06 Alta institución" as UC06
    usecase "UC-07 Modificar institución" as UC07
    usecase "UC-08 Alta curso" as UC08
    usecase "Modalidad presencial" as UC08A
    usecase "Modalidad virtual" as UC08B
    usecase "Modalidad mixta" as UC08C
    usecase "UC-09 Modificar curso" as UC09
    usecase "UC-10 Buscar curso" as UC10
    usecase "UC-11 Baja curso" as UC11
    usecase "UC-12 Asignar docente a curso" as UC12
    usecase "UC-13 Buscar docente" as UC13
    usecase "UC-14 Desasignar docente de curso" as UC14
    usecase "UC-15 Definir días y horarios del curso" as UC15
    usecase "UC-16 Cambiar contraseña de acceso a curso" as UC16
    usecase "UC-17 Unirse a un curso" as UC17
    usecase "UC-18 Habilitar capítulo" as UC18
    usecase "UC-19 Buscar capítulo" as UC19
    usecase "UC-20 Finalizar curso" as UC20

    'Relaciones'
    Administrador --> UC06
    Administrador --> UC07
    Administrador --> UC08
    Administrador --> UC09
    Administrador --> UC11
    UC09 ..> UC10 : <<include>>
    UC11 ..> UC10 : <<include>>
    Administrador --> UC12
    UC12 ..> UC10 : <<include>>
    UC12 ..> UC13 : <<include>>
    Administrador --> UC14
    UC14 ..> UC10 : <<include>>
    UC14 ..> UC13 : <<include>>
    Docente --> UC15
    Docente --> UC16
    Alumno --> UC17
    Docente --> UC18
    UC18 ..> UC19 : <<include>>
    Docente --> UC20
    UC20 ..> UC10 : <<include>>
  }

  package "Progreso y estadísticas" {
    usecase "UC-21 Consultar progreso de alumnos" as UC21
    usecase "Consultar progreso en capítulo" as UC21A
    usecase "UC-22 Generar reporte de progreso" as UC22
    usecase "UC-23 Consultar dificultades de alumnos" as UC23
    usecase "UC-24 Sincronizar progreso de alumno" as UC24
    usecase "UC-25 Actualizar dificultades de alumno" as UC25
    usecase "UC-26 Consultar mi progreso" as UC26
    usecase "UC-27 Consultar mis dificultades" as UC27
    
    'Relaciones'
    Docente --> UC21
    UC21 <.. UC21A : <<extend>>
    Docente --> UC22
    Docente --> UC23
    Videojuego --> UC24
    Videojuego --> UC25
    Alumno --> UC26
    Alumno --> UC27
  }

  package "Gestión de sesiones de refuerzo" {
    usecase "UC-28 Crear sesión de refuerzo" as UC28
    usecase "UC-29 Modificar sesión de refuerzo" as UC29
    usecase "UC-30 Buscar sesión de refuerzo" as UC30
    usecase "UC-31 Cancelar sesión de refuerzo" as UC31
    usecase "UC-32 Indicar asistencia a sesión" as UC32
    
    'Relaciones'
    Docente --> UC28
    Docente --> UC29
    Docente --> UC31
    UC29 ..> UC30 : <<include>>
    UC31 ..> UC30 : <<include>>

    Docente --> UC32
    Alumno --> UC32
    UC32 ..> UC30 : <<include>>
  }

  package "Auditoría" {
    usecase "UC-33 Consultar registros de auditoría" as UC33
    usecase "Exportar registros de auditoría" as UC33A
    
    'Relaciones'
    Administrador --> UC33
    UC33 <.. UC33A : <<extend>>
  }

  package "Seguridad y autenticación" {
    usecase "UC-34 Iniciar sesión" as UC34
    usecase "Iniciar sesión normal" as UC34A
    usecase "Iniciar sesión con Google" as UC34B
    usecase "UC-35 Registrarse" as UC35
    usecase "Registro normal" as UC35A
    usecase "Registro con Google" as UC35B
    usecase "UC-36 Cerrar sesión" as UC36
    
    'Relaciones'
    Administrador --> UC34
    Administrador --> UC36
    Docente --> UC34
    Docente --> UC36
    Alumno --> UC34
    Alumno --> UC35
    Alumno --> UC36
    UC34 <.. UC34A : <<extend>>
    UC34 <.. UC34B : <<extend>>
    UC35 <.. UC35A : <<extend>>
    UC35 <.. UC35B : <<extend>>
    GoogleOAuth2 -up-> UC34B
    GoogleOAuth2 -up-> UC35B
  }

}
@enduml