@startuml SUBSISTEMA_GestionAuditoria
left to right direction

skinparam dpi 150
skinparam usecasePadding 25
skinparam actorPadding 80
skinparam packagePadding 50
skinparam wrapWidth 200

skinparam nodesep 20
skinparam ranksep 100

actor Administrador

package "Plataforma Web"{
    package "Gestión de auditoría"{
        usecase "UC-16 Consultar registros de auditoría" as UC16
        usecase "UC-59 Exportar registros de auditoría" as UC59
    }
}

Administrador --> UC16
UC16 --> UC59 : <<extend>>

@enduml