@startuml SUBSISTEMA_GestionSesionesRefuerzo
left to right direction

skinparam dpi 150
skinparam usecasePadding 25
skinparam actorPadding 80
skinparam packagePadding 50
skinparam wrapWidth 200

skinparam nodesep 20
skinparam ranksep 100

actor Alumno
actor Docente

package "Plataforma Web - PGA"{
    package "Gestión de sesiones de refuerzo" {
        usecase "UC-29 Crear sesión de refuerzo" as UC29
        usecase "UC-30 Modificar sesión de refuerzo" as UC30
        usecase "UC-31 Buscar sesión de refuerzo" as UC31
        usecase "UC-32 Cancelar sesión de refuerzo" as UC32
        usecase "UC-33 Indicar asistencia a sesión" as UC33
    }
}

Docente --> UC29
Docente --> UC30
Docente --> UC32
UC30 ..> UC31 : <<include>>
UC32 ..> UC31 : <<include>>

Docente --> UC33
Alumno --> UC33
UC33 ..> UC31 : <<include>>

@enduml