@startuml SUBSISTEMA_GestionCursos
left to right direction

skinparam dpi 150
skinparam usecasePadding 25
skinparam actorPadding 80
skinparam packagePadding 50
skinparam wrapWidth 200

skinparam nodesep 20
skinparam ranksep 50

actor Alumno
actor Docente
actor Administrador

package "Plataforma Web"{
    package "Gestión de cursos"{
        usecase "UC-10 Alta curso" as UC10
        usecase "UC-11 Modificar curso" as UC11
        usecase "UC-12 Buscar curso" as UC12
        usecase "UC-13 Baja curso" as UC13
        usecase "UC-14 Asignar docente a curso" as UC14
        usecase "UC-15 Buscar docente" as UC15
        usecase "UC-16 Remover docente de curso" as UC16
        usecase "UC-29 Definir días y horarios del curso" as UC29
        usecase "UC-30 Cambiar contraseña de acceso a curso" as UC30
        usecase "UC-31 Aprobar solicitud de ingreso al curso" as UC31
        usecase "UC-32 Habilitar capítulo" as UC32
        usecase "UC-33 Buscar capítulo" as UC33
        usecase "UC-42 Solicitar ingreso a curso" as UC43
    }
}

Administrador --> UC10
Administrador --> UC11
Administrador --> UC13

UC11 ..> UC12 : <<include>>
UC13 ..> UC12 : <<include>>

Administrador --> UC14
Administrador --> UC16
UC14 ..> UC15 : <<include>>
UC14 ..> UC12 : <<include>>
UC16 ..> UC15 : <<include>>
UC16 ..> UC12 : <<include>>

Docente --> UC29
Docente --> UC30
Docente --> UC31
Docente --> UC32
UC32 ..> UC33 : <<include>>

Alumno --> UC42

@enduml