@startuml SUBSISTEMA_ProgresoEstadisticas
left to right direction

skinparam dpi 150
skinparam usecasePadding 25
skinparam actorPadding 80
skinparam packagePadding 50
skinparam wrapWidth 200

skinparam nodesep 20
skinparam ranksep 100

actor Alumno
actor Docente
actor Videojuego

package "Plataforma Web - PGA"{
    package "Progreso y estadísticas" {
        usecase "UC-21 Consultar progreso de alumnos" as UC21
        usecase "UC-22 Consultar progreso en capítulo" as UC22
        usecase "UC-23 Generar reporte de progreso" as UC23
        usecase "UC-24 Consultar dificultades de alumnos" as UC24
        usecase "UC-25 Sincronizar progreso de alumno" as UC25
        usecase "UC-26 Actualizar dificultades de alumno" as UC26
        usecase "UC-27 Consultar mi progreso" as UC27
        usecase "UC-28 Consultar mis dificultades" as UC28
    }
}

Docente --> UC21
UC21 <.. UC22 : <<extend>>

Docente --> UC23
Docente --> UC24

Videojuego --> UC25
Videojuego --> UC26

Alumno --> UC27
Alumno --> UC28