@startuml SUBSISTEMA_GestionInstitucionCursos
left to right direction

skinparam dpi 150
skinparam usecasePadding 25
skinparam actorPadding 80
skinparam packagePadding 50
skinparam wrapWidth 200

skinparam nodesep 20
skinparam ranksep 50

actor Alumno
actor Docente
actor Administrador

package "Plataforma Web - PGA"{
    package "Gestión de institución y cursos" {
        usecase "UC-06 Alta institución" as UC06
        usecase "UC-07 Modificar institución" as UC07
        usecase "UC-08 Alta curso" as UC08
        usecase "UC-09 Modificar curso" as UC09
        usecase "UC-10 Buscar curso" as UC10
        usecase "UC-11 Baja curso" as UC11
        usecase "UC-12 Asignar docente a curso" as UC12
        usecase "UC-13 Buscar docente" as UC13
        usecase "UC-14 Desasignar docente de curso" as UC14
        usecase "UC-15 Definir días y horarios del curso" as UC15
        usecase "UC-16 Cambiar contraseña de acceso a curso" as UC16
        usecase "UC-17 Unirse a un curso" as UC17
        usecase "UC-18 Habilitar capítulo" as UC18
        usecase "UC-19 Buscar capítulo" as UC19
        usecase "UC-20 Finalizar curso" as UC20
    }
}

Administrador --> UC06
Administrador --> UC07

Administrador --> UC08
Administrador --> UC09
Administrador --> UC11
UC09 ..> UC10 : <<include>>
UC11 ..> UC10 : <<include>>

Administrador --> UC12
UC12 ..> UC10 : <<include>>
UC12 ..> UC13 : <<include>>
Administrador --> UC14
UC14 ..> UC10 : <<include>>
UC14 ..> UC13 : <<include>>

Docente --> UC15
Docente --> UC16

Alumno --> UC17
Docente --> UC18
UC18 ..> UC19 : <<include>>
Docente --> UC20
UC20 ..> UC10 : <<include>>

@enduml