@startuml SUBSISTEMA_GestionUsuarios
left to right direction

skinparam dpi 150
skinparam usecasePadding 25
skinparam actorPadding 80
skinparam packagePadding 50
skinparam wrapWidth 200

skinparam nodesep 20
skinparam ranksep 100

actor Alumno
actor Docente
actor Administrador

package "Plataforma Web - PGA"{
    package "Gestión de usuarios" {
        usecase "UC-01 Alta usuario" as UC01
        usecase "UC-02 Modificar usuario" as UC02
        usecase "UC-03 Buscar usuario" as UC03
        usecase "UC-04 Baja usuario" as UC04
        usecase "UC-05 Modificar datos personales" as UC05
    }
}
Administrador --> UC01
Administrador --> UC02
UC02 ..> UC03 : <<include>>
Administrador --> UC04
UC04 ..> UC03 : <<include>>

Alumno --> UC05
Docente --> UC05