@startuml SUBSISTEMA_GestionUsuarios
left to right direction

skinparam dpi 150
skinparam usecasePadding 25
skinparam actorPadding 80
skinparam packagePadding 50
skinparam wrapWidth 200

skinparam nodesep 20
skinparam ranksep 100

actor Alumno
actor Docente
actor Administrador
actor "Google OAuth 2.0" as GoogleOAuth2

package "Plataforma Web"{
    package "Gestión de usuarios"{
        usecase "UC-01 Alta usuario" as UC01
        usecase "UC-02 Modificar usuario" as UC02
        usecase "UC-03 Buscar usuario" as UC03
        usecase "UC-04 Baja usuario" as UC04
        usecase "UC-05 Iniciar sesión" as UC05
        usecase "UC-32 Registrarse en la plataforma" as UC32
        usecase "UC-33 Registro normal" as UC33
        usecase "UC-34 Registro con Google" as UC34
        usecase "UC-35 Iniciar sesión en la plataforma web" as UC35
        usecase "UC-36 Iniciar sesión normal" as UC36
        usecase "UC-37 Iniciar sesión con Google" as UC37
        usecase "UC-31 Modificar datos personales" as UC31
    }

}
Administrador --> UC01
Administrador --> UC02
UC02 --> UC03 : <<include>>
Administrador --> UC04
UC04 --> UC03 : <<include>>
Administrador --> UC05

Alumno --> UC31
Alumno --> UC32
UC32 --> UC33 : <<extend>>
UC32 --> UC34 : <<extend>>
Alumno --> UC35
UC35 --> UC36 : <<extend>>
UC35 --> UC37 : <<extend>>

Docente --> UC31
Docente --> UC05

GoogleOAuth2 -up-> UC34
GoogleOAuth2 -up-> UC37