@startuml SUBSISTEMA_SeguimientoAcademico
left to right direction

skinparam dpi 150
skinparam usecasePadding 25
skinparam actorPadding 80
skinparam packagePadding 50
skinparam wrapWidth 200

skinparam nodesep 20
skinparam ranksep 100

actor Alumno
actor Docente

package "Plataforma Web"{
    package "Seguimiento académico"{
        usecase "UC-17 Consultar progreso de alumnos" as UC17
        usecase "UC-18 Ver progreso general (historia)" as UC18
        usecase "UC-19 Ver progreso por capítulo" as UC19
        usecase "UC-20 Generar reporte de progreso" as UC20
        usecase "UC-21 Crear sesión de refuerzo" as UC21
        usecase "UC-22 Modificar sesión de refuerzo" as UC22
        usecase "UC-23 Buscar sesión de refuerzo" as UC23
        usecase "UC-24 Cancelar sesión de refuerzo" as UC24
        usecase "UC-25 Aceptar sesión de refuerzo automática" as UC25
        usecase "UC-29 Habilitar capítulo" as UC29
        usecase "UC-30 Buscar capítulo" as UC30
        usecase "UC-38 Ver progreso en la web" as UC38
        usecase "UC-40 Confirmar asistencia a sesión de refuerzo" as UC40
    }
}

Docente --> UC17
UC17 --> UC18 : <<include>>
UC17 --> UC19 : <<include>>

Docente --> UC20
Docente --> UC21
Docente --> UC22
Docente --> UC24
UC22 --> UC23 : <<include>>
UC24 --> UC23 : <<include>>
Docente --> UC25
Docente --> UC29
UC29 --> UC30 : <<include>>

Alumno --> UC38
Alumno --> UC40 

@enduml